In [2]:
# creating numpy array (one dimensional)
import numpy as np
a=[1,2,3,4,5]
b=np.array(a)
print(b)
print(type(b),"Array: ",b)

[1 2 3 4 5]
<class 'numpy.ndarray'> Array:  [1 2 3 4 5]


In [3]:
# even we can do it Directly 
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
# array carrying only one value
a=np.array([5,])
print(type(a),"\nArray: ",a)

<class 'numpy.ndarray'> 
Array:  [5]


In [8]:
# to check the dimensions 
a=np.array([5,])
print(type(a),"\nArray: ",a)
print(a.ndim)

<class 'numpy.ndarray'> 
Array:  [5]
1


In [9]:
# user define array 
a=[]
n=int(input("enter range: "))
for i in range(n):
    b=eval(input("enter value: "))
    a.append(b)
c=np.array(a)
print("Array: ",c)
print(type(c))

enter range: 5
enter value: 21
enter value: 24
enter value: 25
enter value: 26
enter value: 23
Array:  [21 24 25 26 23]
<class 'numpy.ndarray'>


In [14]:
# creating Two Dimensional Array
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print("Array: \n",b)
print("Dimensions: ",b.ndim)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions:  2


In [15]:
# we can do it directly also
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n",a)
print("Dimensions: ",a.ndim)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions:  2


In [17]:
# to check the shape of the array 
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n",a)
print("Shape of the array: ",a.shape)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array:  (3, 3)


In [18]:
# will create 3 Dimesional Array 
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array: \n",a)
print("dimensions: ",a.ndim)

Array: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensions:  3


In [21]:
# check the shape of 3D and reshape it
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array: \n",a)
print("Shape of the array: ",a.shape)
print("reshaping the Array: \n",a.reshape(3,1,3))


Array: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape of the array:  (1, 3, 3)
reshaping the Array: 
 [[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [22]:
# Numpy functions
# 1.zeros
import numpy as np
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [24]:
import numpy as np
a = np.zeros(5)+2
a

array([2., 2., 2., 2., 2.])

In [26]:
# 2D Dimesnional 
import numpy as np
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# 2D Dimesnional and reshaping
import numpy as np
a=np.zeros((2,3)).reshape(3,2)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
# 3D dimensional 
import numpy as np 
a=np.zeros((3,3)).reshape(3,1,3)
a

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [30]:
# Ones()
import numpy as np
a= np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [31]:
import numpy as np 
a = np.ones(5)*5
a

array([5., 5., 5., 5., 5.])

In [33]:
import numpy as np
a=np.ones((2,4))
print(a)
print(a.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [35]:
import numpy as np
a=np.ones((2,4)).reshape(4,2)
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:

import numpy as np
a=np.ones((2,4)).reshape(2,1,4)
a

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

In [38]:
# eye Function
import numpy as np
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
import numpy as np
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [40]:
import numpy as np
a=np.eye(1,3)
a

array([[1., 0., 0.]])

In [41]:
import numpy as np
a=np.eye(3,1)
a

array([[1.],
       [0.],
       [0.]])

In [42]:
import numpy as np
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [43]:
import numpy as np
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
import numpy as np
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
# Diag Functions
import numpy as np
a=np.diag([1,5,9])
a

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [47]:
import numpy as np 
a=np.diag([5,7,3,4])
a

array([[5, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [48]:
# static way
import numpy as np
a=[]
for i in range(1,11):
    a.append(i)
b=np.diag(a)
b

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [49]:
# to know the diagonal value
print(np.diag(b))

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
# user define 
a=[]
n=eval(input("enter range: "))
for i in range(n):
    val=eval(input("enter value: "))
    a.append(val)
b=np.diag(a)
print(b)
print("\nDiagonal Value are: ",np.diag(b))

enter range: 5
enter value: 21
enter value: 24
enter value: 25
enter value: 26
enter value: 23
[[21  0  0  0  0]
 [ 0 24  0  0  0]
 [ 0  0 25  0  0]
 [ 0  0  0 26  0]
 [ 0  0  0  0 23]]

Diagonal Value are:  [21 24 25 26 23]


In [53]:
# randint()
# this functions generates random number from a given range 
import numpy as np 
a=np.random.randint(1,100,9)
a

array([90, 49,  7, 62,  2, 16, 98, 15, 49])

In [64]:
# 2d
import numpy as np 
a=np.random.randint(1,100,9).reshape(3,3)
a

array([[ 8, 11,  8],
       [97, 60, 16],
       [70, 63, 14]])

In [69]:
# 3d
import numpy as np 
a=np.random.randint(1,100,9).reshape(3,1,3)
a

array([[[ 4, 10, 54]],

       [[10, 41, 70]],

       [[90, 63, 58]]])

In [70]:
# rand()
# it generates a random value between 0 to 1
import numpy as np
a=np.random.rand(5)
a

array([0.09281678, 0.85691144, 0.66102102, 0.52422544, 0.07461948])

In [71]:
import numpy as np
a=np.random.rand(5).reshape(5,1)
a

array([[0.54519228],
       [0.11859108],
       [0.49721919],
       [0.69276984],
       [0.67288639]])

In [74]:
import numpy as np
a=np.random.rand(3,3,3)
print(a)
print("Dimensions: ",a.ndim)
print("Diagnoal Value: ",np.diag(a))
# the reason i got this error , it says that we need 1D array or 2D Array
# not 3D Array

[[[0.63764339 0.88265885 0.65149711]
  [0.27049314 0.92530958 0.36320834]
  [0.9471536  0.85130918 0.96117358]]

 [[0.94197581 0.67416668 0.39711472]
  [0.74146867 0.56930019 0.20206737]
  [0.20021384 0.78271986 0.81780431]]

 [[0.08170152 0.42614562 0.27632656]
  [0.37961727 0.41325839 0.52624378]
  [0.29194547 0.8998295  0.50476441]]]
Dimensions:  3


ValueError: Input must be 1- or 2-d.

In [75]:
import numpy as np
a=np.random.rand(3,3)
print(a)
print("Dimensions: ",a.ndim)
print("Diagnoal Value: ",np.diag(a))

[[0.97025457 0.3625739  0.02330217]
 [0.41775706 0.25861442 0.02172816]
 [0.23561938 0.26132069 0.58927819]]
Dimensions:  2
Diagnoal Value:  [0.97025457 0.25861442 0.58927819]


In [77]:
# randn function 
# it geneartes a random value close to Zero 0,this may return a positive or negative value
import numpy as np
a = np.random.randn(5)
a

array([ 1.54297248, -0.19821232,  0.1266968 ,  0.10342283,  1.07685723])

In [78]:
import numpy as np
a = np.random.randn(3,3)
a

array([[-0.04108927,  1.66860309,  0.98597691],
       [ 0.56259726,  1.48101811, -2.10479351],
       [-0.32344845, -0.3770358 ,  0.85330877]])

In [79]:
import numpy as np 
a=np.random.randn(5).reshape(5,1)
a

array([[ 0.56015908],
       [ 0.30102474],
       [-0.05849343],
       [-1.14183333],
       [ 1.03861453]])

In [80]:
import numpy as np 
a= np.random.randn(5,2)
a

array([[ 1.07424459, -0.96613023],
       [-0.17130359, -0.33453799],
       [ 0.03435219, -1.40208192],
       [ 2.01202723,  1.96232344],
       [ 0.88489275,  1.74679606]])

In [82]:
# indexing in 1d array 
import numpy as np
a=[]
n=eval(input("enter range: "))
for i in range(n):
    val=eval(input("enter value: "))
    a.append(val)
b=np.array(a)
for i in range(b.size):
    print(b[i])

enter range: 5
enter value: 21
enter value: 24
enter value: 26
enter value: 23
enter value: 21
21
24
26
23
21


In [83]:
# array, size, indexing
import numpy as np
a=[]
n=eval(input("enter range: "))
for i in range(n):
    val=eval(input("enter value: "))
    a.append(val)
b=np.array(a)
print("Array: ",b,"Size of the Array: ",b.size)
for i in range(b.size):
    print(b[i])

enter range: 3
enter value: 21
enter value: 25
enter value: 23
Array:  [21 25 23] Size of the Array:  3
21
25
23


In [87]:
# find sum from the above 
# array, size, indexing
import numpy as np
a=[]
n=eval(input("enter range: "))
cnt=1
for i in range(n):
    val=eval(input(f"enter value {cnt}: "))
    a.append(val)
    cnt+=1
b=np.array(a)
print("Array: ",b,"Size of the Array: ",b.size)
sum=0
for i in range(b.size):
    print(b[i])
    sum+=b[i]
print("The total sum of the given Array: ",sum)

enter range: 5
enter value 1: 21
enter value 2: 24
enter value 3: 25
enter value 4: 26
enter value 5: 2
Array:  [21 24 25 26  2] Size of the Array:  5
21
24
25
26
2
The total sum of the given Array:  98


In [90]:
# Slicing in 1D Array 
import numpy as np 
a=[]
n= eval(input("enter range: "))
cnt=1
for i in range(n):
    val=eval(input(f"enter value {cnt}: "))
    a.append(val)
    cnt+=1
b=np.array(a)
print(f"Array: {b} and Size of the Array: {b.size}")
for i in range(b.size):
    print(b[i])
arr2=b[2:4]
arr3=b[::2]
print(arr2)
print(arr3)
print(arr2[::2])
print(arr2[::-1])

enter range: 5
enter value 1: 21
enter value 2: 24
enter value 3: 25
enter value 4: 26
enter value 5: 23
Array: [21 24 25 26 23] and Size of the Array: 5
21
24
25
26
23
[25 26]
[21 25 23]
[25]
[26 25]


In [92]:
# Reshaping the Array 
import numpy as np
a=np.random.randint(1,50,12)
# will print 12 random numbers 
print("Array: ",a)

Array:  [41 40 49 30  4 17 49  5 38 48 30 38]


In [93]:
# reshape the Array 
a.reshape(6,2)

array([[41, 40],
       [49, 30],
       [ 4, 17],
       [49,  5],
       [38, 48],
       [30, 38]])

In [94]:
a.reshape(2,6)

array([[41, 40, 49, 30,  4, 17],
       [49,  5, 38, 48, 30, 38]])

In [95]:
a.reshape(2,2,3)

array([[[41, 40, 49],
        [30,  4, 17]],

       [[49,  5, 38],
        [48, 30, 38]]])

In [99]:
a.reshape(2,3,2)

array([[[41, 40],
        [49, 30],
        [ 4, 17]],

       [[49,  5],
        [38, 48],
        [30, 38]]])

In [100]:
import numpy as np
a=np.random.randint(1,100,12)
print("--2d Array-- \n",a.reshape(6,2))
print("--1d Array-- \n",a.reshape(12))
print("--3d Array-- \n",a.reshape(2,2,3),"\n","number of dimensions: ",a.shape)
print("--3d Array-- \n",a.reshape(2,3,2))

--2d Array-- 
 [[32 66]
 [93 50]
 [61 57]
 [56 80]
 [85 95]
 [ 3 31]]
--1d Array-- 
 [32 66 93 50 61 57 56 80 85 95  3 31]
--3d Array-- 
 [[[32 66 93]
  [50 61 57]]

 [[56 80 85]
  [95  3 31]]] 
 number of dimensions:  (12,)
--3d Array-- 
 [[[32 66]
  [93 50]
  [61 57]]

 [[56 80]
  [85 95]
  [ 3 31]]]


In [101]:
import numpy as np
a=np.random.randint(1,100,12)
print("--2d Array-- \n",a.reshape(6,-1))
print("--2d Array-- \n",a.reshape(4,-1))
print("--2d Array-- \n",a.reshape(3,-1))
print("--2d Array-- \n",a.reshape(-1,2))
print("--2d Array-- \n",a.reshape(-1,4))
print("--2d Array-- \n",a.reshape(-1,3))
print("--1d Array-- \n",a.reshape(12))
print("--3d Array-- \n",a.reshape(2,2,3),"\n","number of dimensions: ",a.shape)

--2d Array-- 
 [[49 36]
 [23 97]
 [55 27]
 [85 76]
 [61 37]
 [49 86]]
--2d Array-- 
 [[49 36 23]
 [97 55 27]
 [85 76 61]
 [37 49 86]]
--2d Array-- 
 [[49 36 23 97]
 [55 27 85 76]
 [61 37 49 86]]
--2d Array-- 
 [[49 36]
 [23 97]
 [55 27]
 [85 76]
 [61 37]
 [49 86]]
--2d Array-- 
 [[49 36 23 97]
 [55 27 85 76]
 [61 37 49 86]]
--2d Array-- 
 [[49 36 23]
 [97 55 27]
 [85 76 61]
 [37 49 86]]
--1d Array-- 
 [49 36 23 97 55 27 85 76 61 37 49 86]
--3d Array-- 
 [[[49 36 23]
  [97 55 27]]

 [[85 76 61]
  [37 49 86]]] 
 number of dimensions:  (12,)


In [115]:
# seed function 
import numpy as np 
np.random.seed(2)
a=np.random.randint(1,50,50)
a

array([41, 16, 46,  9, 23, 44, 19, 12, 41,  8, 35, 32, 12, 22, 48, 32, 27,
       21, 38, 40,  4, 39,  5, 43, 44, 40, 39, 43, 34,  4,  6, 25,  5, 47,
        7, 32, 20, 32,  3, 17, 47, 13,  5, 27, 16, 40, 47,  9, 46, 16])

In [118]:
# if i try to remove this seed function 
# the nos will get change 
import numpy as np
# np.random.seed(2)
a=np.random.randint(1,100,10)
a

array([87, 71, 20, 57, 83,  2, 69, 41, 82, 62])

In [120]:
import numpy as np
np.random.seed(11)
a=np.random.randint(1,100,12)
print("Array: ",a)
print("Size of the Array: ",a.size)

Array:  [26 64 81 92 82 56 14 77 34 72 83 25]
Size of the Array:  12


In [122]:
# indexing in 2d array 
import numpy as np
matrix=[]
row=eval(input("enter rows: "))
col=eval(input("enter columns: "))
for i in range(row):
    a=[]
    for j in range(col):
        val=eval(input("enter value: "))
        a.append(val)
    matrix.append(a)
# print(matrix)
for i in range(row):
    for j in range(col):
        print(matrix[i][j],end=" ")
    print()
b=np.array(matrix)
print("Array: \n",b)

enter rows: 3
enter columns: 2
enter value: 1
enter value: 2
enter value: 3
enter value: 1
enter value: 2
enter value: 3
1 2 
3 1 
2 3 
Array: 
 [[1 2]
 [3 1]
 [2 3]]


In [123]:
import numpy as np 
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [125]:
print(a[:2])
# strating two Rows

[[10 20 30]
 [40 50 60]]


In [126]:
print(a[:2,1:3])

[[20 30]
 [50 60]]


In [127]:
print(a[1:3,1:3])

[[50 60]
 [80 90]]


In [128]:
import numpy as np
np.random.seed(111)
a=np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [129]:
print(a[2:4,2:4])

[[442   8]
 [369 217]]


In [132]:
# view 
import numpy as np 
a=np.arange(1,10)
b=a[3:6]
b[:]=0
a

array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [134]:
# copy
import numpy as np 
a=np.arange(1,10)
b=a[3:6].copy()
print(b)
b[:]=0
print(a)

[4 5 6]
[1 2 3 4 5 6 7 8 9]


In [135]:
# arange()
import numpy as np 
a=np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [138]:
# static way 
import numpy as np 
a=np.arange(1,16)
print("Array: ",a)
# conditional based statement
print(a>10)
print("Numberes greater than 10 in the array: ",a[a>10])

Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[False False False False False False False False False False  True  True
  True  True  True]
Numberes greater than 10 in the array:  [11 12 13 14 15]


In [140]:
# Dynamic Way
import numpy as np 
a=np.arange(eval(input("enter starting no: ")),eval(input("enter ending no"))+1)
print(a)
print(a[a>eval(input("enter greater condition no: "))])
print(a[a<eval(input("enter smaller condition no: "))])


enter starting no: 1
enter ending no10
[ 1  2  3  4  5  6  7  8  9 10]
enter greater condition no: 5
[ 6  7  8  9 10]
enter smaller condition no: 5
[1 2 3 4]


In [141]:
import numpy as np 
a=np.arange(1,16)
print(a[a%2==0])

[ 2  4  6  8 10 12 14]


In [142]:
# Operations on Array 
a=np.arange(1,5)
a=a*2
a

array([2, 4, 6, 8])

In [143]:
a=a+2
a

array([ 4,  6,  8, 10])

In [144]:
a=a**3
a

array([  64,  216,  512, 1000], dtype=int32)

In [146]:
a=a/0
a
# if numpy array divided by zero then it gives infinity and not any error

array([inf, inf, inf, inf])

In [149]:
# operation onn 2 array 
import numpy as np
a=np.arange(1,5).reshape(2,2)
b=np.arange(5,9).reshape(2,2)
print("Array a: \n",a)
print("Array b: \n",b)

Array a: 
 [[1 2]
 [3 4]]
Array b: 
 [[5 6]
 [7 8]]


In [150]:
a+b

array([[ 6,  8],
       [10, 12]])

In [151]:
b-a

array([[4, 4],
       [4, 4]])

In [152]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [153]:
a*b

array([[ 5, 12],
       [21, 32]])

In [154]:
# dot functions gives proper matrix result
a.dot(b)

array([[19, 22],
       [43, 50]])

In [155]:
b.dot(a)

array([[23, 34],
       [31, 46]])

#### Some more Functions of Numpy
![image.png](attachment:image.png)

In [156]:
from numpy import *
a=np.arange(1,15)
print(min(a))
print(max(a))
print(argmin(a))
print(argmax(a))
print(sqrt(a))
print(square(a))
print(sin(a))
print(cos(a))

1
14
0
13
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722]


In [157]:
# creating 2d array with fixed datatype
import numpy as np
np.random.seed(122)
a=np.random.randint(1,21,9).reshape(3,1,3)
a

array([[[16, 11, 13]],

       [[17, 13, 16]],

       [[ 3, 16, 11]]])

In [158]:
np.sum(a)

116

In [159]:
a.sum()

116

In [160]:
np.min(a)

3

In [162]:
a.min()

3

In [163]:
a.mean()

12.88888888888889

In [164]:
a.max()

17

In [165]:
a.cumsum()

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [166]:
np.cumsum(a,axis=0)

array([[[16, 11, 13]],

       [[33, 24, 29]],

       [[36, 40, 40]]], dtype=int32)

In [167]:
# creating 2d array with fixed datatype
import numpy as np
np.random.seed(122)
a=np.random.randint(1,21,10)
a

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [176]:
# In shuffle() the values will be same but it will shuffle
np.random.shuffle(a)
a

array([11, 17, 13, 16, 16,  3, 13, 10, 11, 16])

In [181]:
# it will give the unique value not the repetetive one
np.unique(a)

array([ 3, 10, 11, 13, 16, 17])

In [182]:
# size - counts the unique counts of elements
np.unique(a).size

6

In [183]:
import numpy as np
a=np.array([10,20,30,40,10,20,50])
a

array([10, 20, 30, 40, 10, 20, 50])

In [184]:
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [190]:
# python numpy Stacking
import numpy as  np 
a=np.arange(1,5)
b=np.arange(5,9)
print(a)
print(b)
print(np.hstack((a,b)))

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [191]:
print(np.vstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]


In [192]:
np.hstack((b,a))

array([5, 6, 7, 8, 1, 2, 3, 4])

In [193]:
np.vstack((b,a))

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [199]:
import numpy as np
np.random.seed(122)
a=np.random.randint(1,21,9).reshape(3,3)
b=np.random.randint(31,51,9).reshape(3,3)
print("Array a")
print(a)
print()
print("Array b")
print(b)

Array a
[[16 11 13]
 [17 13 16]
 [ 3 16 11]]

Array b
[[40 37 45]
 [34 35 50]
 [50 44 31]]


In [200]:
np.hstack((a,b))

array([[16, 11, 13, 40, 37, 45],
       [17, 13, 16, 34, 35, 50],
       [ 3, 16, 11, 50, 44, 31]])

In [201]:
np.hstack((b,a))

array([[40, 37, 45, 16, 11, 13],
       [34, 35, 50, 17, 13, 16],
       [50, 44, 31,  3, 16, 11]])

In [202]:
np.vstack((a,b))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [40, 37, 45],
       [34, 35, 50],
       [50, 44, 31]])

In [203]:
np.vstack((b,a))

array([[40, 37, 45],
       [34, 35, 50],
       [50, 44, 31],
       [16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [204]:
# write a statement to import numpy
import numpy as np
# or
from numpy import *

In [ ]:
# create an Array using Numpy
a=np.array([1,2,3,4])
a
# you can also create array with user input

In [205]:
# create an array of 10 random Integers
import numpy as np 
a=np.random.randint(1,100,10)
a

array([46, 21, 16, 82, 61, 76, 64, 43,  7, 49])

In [206]:
# create an array of elements from 10-20
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [209]:
a=np.ones(10)*5
print(a)
print(a.size)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
10


In [211]:
# create a one dimensional array and convert that into 3*3 matrix
np.random.randint(1,100,9).reshape(3,3)

array([[20, 32, 76],
       [15, 93, 90],
       [ 6, 14, 10]])

In [210]:
# create a one dimensional array and convert that into 3d array 
np.random.randint(1,100,9).reshape(3,1,3)

array([[[86, 41, 88]],

       [[ 9, 10, 83]],

       [[51, 86, 41]]])

In [216]:
# create an array and then convert all the even numbers with 0
a=np.arange(1,51)
b=a%2==0
a[b]=0
a

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49,  0])

In [217]:
# create a 2d array of size 3*3 but all the elements should be between 0 and 1.
np.random.rand(3,3)

array([[0.17080412, 0.01541429, 0.2656121 ],
       [0.82728314, 0.83457956, 0.86875138],
       [0.9933149 , 0.05004751, 0.10903951]])

In [218]:
# perform the following slicing 
import numpy as np
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [219]:
a[1:,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [220]:
# concatenate 2D array horizontally and vertically 
import numpy as np
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(np.hstack((a,b)))
print(np.hstack((b,a)))
print(np.vstack((a,b)))
print(np.vstack((b,a)))

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[10 11 12  1  2  3]
 [13 14 15  4  5  6]
 [16 17 18  7  8  9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [224]:
# timeit
%timeit 2+3

10.7 ns ± 0.233 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [228]:
%%timeit 
a=[]
for i in range(1,15):
    a.append(i*10)

1.31 µs ± 3.76 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [229]:
%timeit [i**2 for i in range(1,11)]

2.42 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [230]:
import numpy as np
%timeit np.arange(1,11)**2

1.26 µs ± 40.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [231]:
import numpy as np
a=np.array([10,20,30,40,50,40,40])
x=np.where(a==40)
print(x)
# which means that the value 40 is present at index 3,5 and 6

(array([3, 5, 6], dtype=int64),)


In [232]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
result = np.where(a%2==0)
print("Here are the index which accepts this condition(a%2==0):\n",result)

Here are the index which accepts this condition(a%2==0):
 (array([1, 3, 5, 7, 9], dtype=int64),)


In [233]:
import numpy as np
a=np.arange(1,11)
res= np.where(a%2==0)
print(res)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [234]:
# left to right 
import numpy as np
a=np.array([2,5,8,9,13])
x=np.searchsorted(a,7)
print(x)

2


In [235]:
# right to left 
import numpy as np 
a=np.array([2,5,8,9,13])
x=np.searchsorted(a,7,side="right")
print(x)

2


 - It doesnt matter from which side you do the SearchSort, The main motive is that it will return the index no. that where should the element get placed.