#### What is an Array
 - An Array is a Data Structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While Python lists can Contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.
 - The Reason we use Array because Arrays Operations are very very fast.

In [2]:
# lets initially install numpy
!pip install numpy

In [3]:
# lets initially import numpy
import numpy as np

In [4]:
mylis=[1,2,3,4,5]
arr=np.array(mylis)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5]


In [8]:
arr.shape

(5,)

In [9]:
list1=[1,2,3,4,5]
list2=[5,4,3,2,1]
list3=[1,2,3,4,5]

arr2=np.array([list1,list2,list3])
arr2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [10]:
arr2.shape

(3, 5)

In [11]:
arr2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [4, 3, 2],
       [1, 1, 2],
       [3, 4, 5]])

In [12]:
print("The shape of the Array: ",arr2.shape)

The shape of the Array:  (3, 5)


In [13]:
print("The total element in the Array: ",arr2.size)

The total element in the Array:  15


In [14]:
print("The total Dimensions in the Array: ",arr2.ndim)

The total Dimensions in the Array:  2


#### You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [15]:
import numpy as np 
a = np.arange(24) 
a.ndim

1

In [16]:
b = a.reshape(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [17]:
arr2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [18]:
# indexing
arr= arr2

In [19]:
arr

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [20]:
arr[0:2,0:2]

array([[1, 2],
       [5, 4]])

In [21]:
arr[1:,3:]

array([[2, 1],
       [4, 5]])

In [22]:
arr[1:,1:4]

array([[4, 3, 2],
       [2, 3, 4]])

#### Some in built function in Array 

In [23]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [24]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [26]:
# multidimensional Arrays indexing
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[9,7,6,8,9]
arr=np.array([list1,list2,list3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [27]:
arr[1:,0:2]

array([[2, 3],
       [9, 7]])

In [28]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr=np.arange(0,21,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [30]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
a=np.arange(1,21,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [32]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [33]:
np.linspace(1,10,51)

array([ 1.  ,  1.18,  1.36,  1.54,  1.72,  1.9 ,  2.08,  2.26,  2.44,
        2.62,  2.8 ,  2.98,  3.16,  3.34,  3.52,  3.7 ,  3.88,  4.06,
        4.24,  4.42,  4.6 ,  4.78,  4.96,  5.14,  5.32,  5.5 ,  5.68,
        5.86,  6.04,  6.22,  6.4 ,  6.58,  6.76,  6.94,  7.12,  7.3 ,
        7.48,  7.66,  7.84,  8.02,  8.2 ,  8.38,  8.56,  8.74,  8.92,
        9.1 ,  9.28,  9.46,  9.64,  9.82, 10.  ])

In [34]:
np.linspace(0,10,num=10,endpoint=True,retstep=True,dtype=int)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]), 1.1111111111111112)

In [35]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
arr[2:]=100
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [38]:
# to copy an array  copy() function and broadcasting

arr2=arr.copy()
arr2 

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [42]:
# some condition very useful in Exploratory data Analysis
arr=np.array([1,2,3,4,5,6,7,8,9])
# val=2
print(arr>2) # will get Boolean value in output
print(arr<2) # will get Boolean value in output

[False False  True  True  True  True  True  True  True]
[ True False False False False False False False False]


In [44]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [40]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
# some more inbuilt functions
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [63]:
arr=np.ones((4),dtype=int)
print(arr)

[1 1 1 1]


In [66]:
arr=np.ones((4),dtype=str)
print(arr)

['1' '1' '1' '1']


In [68]:
arr=np.zeros((5,2),dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [69]:
# randome Distribution
arr=np.random.rand(3,2)
print(arr)

[[0.68634793 0.28151712]
 [0.02112866 0.93133557]
 [0.94221052 0.55509724]]


In [70]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [73]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
    
    Paramete

In [72]:
print(np.random.randn())

-1.1031030737005718


In [45]:
np.random.randint(0,100,8).reshape(2,4)

array([[46, 91,  4, 99],
       [23, 40,  4, 37]])

In [46]:
np.random.random_sample((1,5))

array([[0.4759392 , 0.95309174, 0.22546062, 0.74863768, 0.10502888]])