In [1]:
# let initailly install numpy 
!pip install numpy

In [2]:
# lets import numpy
import numpy as np

In [4]:
mylis=[1,2,3,4,5]
arr=np.array(mylis)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
list1=[1,2,3,4,5]
list2=[5,4,3,2,1]
list3=[1,2,3,4,5]

arr2=np.array([list1,list2,list3])
arr2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5]])

In [8]:
arr2.size

15

In [10]:
arr2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [4, 3, 2],
       [1, 1, 2],
       [3, 4, 5]])

In [14]:
arr2=arr2.reshape(5,1,3)
arr2

array([[[1, 2, 3]],

       [[4, 5, 5]],

       [[4, 3, 2]],

       [[1, 1, 2]],

       [[3, 4, 5]]])

In [15]:
print("The shape of the Array: ",arr2.shape)

The shape of the Array:  (5, 1, 3)


In [16]:
print("The total element in the Array: ",arr2.size)

The total element in the Array:  15


In [17]:
print("The total Dimensions in the Array: ",arr2.ndim)

The total Dimensions in the Array:  3


In [18]:
import numpy as np 
a = np.arange(24) 
a.ndim

1

In [19]:
b = a.reshape(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [20]:
arr2

array([[[1, 2, 3]],

       [[4, 5, 5]],

       [[4, 3, 2]],

       [[1, 1, 2]],

       [[3, 4, 5]]])

In [21]:
# indexing
arr= arr2

In [22]:
arr

array([[[1, 2, 3]],

       [[4, 5, 5]],

       [[4, 3, 2]],

       [[1, 1, 2]],

       [[3, 4, 5]]])

In [29]:
arr[:,0:1]

array([[[1, 2, 3]],

       [[4, 5, 5]],

       [[4, 3, 2]],

       [[1, 1, 2]],

       [[3, 4, 5]]])

In [30]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [31]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
# multidimensional Arrays indexing
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[9,7,6,8,9]
arr=np.array([list1,list2,list3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [33]:
arr[1:,0:2]

array([[2, 3],
       [9, 7]])

In [34]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr=np.arange(0,21,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [36]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [37]:
a=np.arange(1,21,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [40]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [39]:
np.linspace(1,10,51)

array([ 1.  ,  1.18,  1.36,  1.54,  1.72,  1.9 ,  2.08,  2.26,  2.44,
        2.62,  2.8 ,  2.98,  3.16,  3.34,  3.52,  3.7 ,  3.88,  4.06,
        4.24,  4.42,  4.6 ,  4.78,  4.96,  5.14,  5.32,  5.5 ,  5.68,
        5.86,  6.04,  6.22,  6.4 ,  6.58,  6.76,  6.94,  7.12,  7.3 ,
        7.48,  7.66,  7.84,  8.02,  8.2 ,  8.38,  8.56,  8.74,  8.92,
        9.1 ,  9.28,  9.46,  9.64,  9.82, 10.  ])

In [41]:
np.linspace(0,10,num=10,endpoint=True,retstep=True,dtype=int)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10]), 1.1111111111111112)

In [42]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
arr[2:]=100
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [44]:
# to copy an array  copy() function and broadcasting

arr2=arr.copy()
arr2 

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [45]:
# some condition very useful in Exploratory data Analysis
arr=np.array([1,2,3,4,5,6,7,8,9])
# val=2
print(arr>2) # will get Boolean value in output
print(arr<2) # will get Boolean value in output

[False False  True  True  True  True  True  True  True]
[ True False False False False False False False False]


In [46]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [47]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [49]:
arr=np.ones((4),dtype=int)
print(arr)

[1 1 1 1]


In [50]:
arr=np.ones((4),dtype=str)
print(arr)

['1' '1' '1' '1']


In [51]:
arr=np.zeros((5,2),dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [52]:
# randome Distribution
arr=np.random.rand(3,2)
print(arr)

[[0.23126299 0.02238676]
 [0.53976834 0.22121414]
 [0.00290194 0.37952527]]
