Numpy- Numerical Python 

Advantages of numpy Arrays:
 - Allows several Mathematical Operations
 - Faster Operations

Numpy is python Librray, Library are nothing but premade function or premade classes which are stored in a Python File

In [1]:
import numpy as np

In [2]:
# lets check the running time of List and Numpy Array
from time import process_time

In [6]:
# time taken by a list 
a=[i for i in range(10000)]

starttime = process_time()

a=[i+5 for i in a]

endtime = process_time()

print(endtime-starttime)

0.0


In [7]:
# let check with Numpy array 
a=np.array([i for i in range(10000)])

starttime=process_time()

a+=5 # a=a+5

endtime=process_time()

print(endtime-starttime)

0.0


In [9]:
#  creating numpy arrays 
# list 
a=[1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
# numpy array 
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# creating 1d array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
# we can check shape of this numpy array
# this shape function array will give us 
# rows and columns of that particular array
a.shape

(4,)

In [13]:
# to check the dimensions of the array
print(a.ndim)

1


In [14]:
# lets create two dimensionnal array 
# 2d array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
print(b.shape)

(2, 4)


In [20]:
# let create anpther array with float dtype
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [21]:
print(c.ndim)

2


In [22]:
# place holders in array 
# initial holders in Numpy arrays 
# create a numpy array of zeros
a=np.zeros((4,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# creat5e nump array of ones
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# create an array of an particular value
c=np.full((5,4),10)
# here 5,4 is matrix shape (5 rows and 4 columns)
# and 10 is the value for that array
print(c)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [27]:
# create an identity matrix
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
b=np.eye(6)
print(b)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [49]:
# create a numpy array with random values
b=np.random.random((3,4))
print(b)
# the value will lie between 0 to 1

[[0.34470892 0.42221712 0.66346068 0.40201735]
 [0.42369953 0.41537643 0.73550524 0.36463227]
 [0.07822622 0.11555556 0.61053675 0.00851903]]


In [57]:
# create a random array with random integers within a specific range 
c=np.random.randint(10,100,(3,5))
print(c)

[[71 33 77 32 65]
 [15 76 62 75 83]
 [33 83 38 66 17]]


In [64]:
# craete and array of evenly spaced values
d=np.linspace(10,30,5)
print(d)
# but all the these 5 values from the range 10 to 30 will be evenly spaced


[10. 15. 20. 25. 30.]


In [65]:
e=np.linspace(10,30,6)
print(e)

[10. 14. 18. 22. 26. 30.]


In [66]:
# another method of getting evenly spaced values
# array of evenly spaced values
# specifying the steps
a=np.arange(10,30,5)
# here the step value is 5
print(a)

[10 15 20 25]


In [67]:
# convert a list to a numpy array 
list2 = [10,20,20,20,50]
# print(list2)
arr=np.asarray(list2)
print(arr)
print(type(arr))

[10 20 20 20 50]
<class 'numpy.ndarray'>


In [68]:
# Analysing a numpy array 
# analysing is nothing but getting information from that particular Array 
# just inspecting an array
c=np.random.randint(10,90,(5,5))
print(c)

[[37 43 59 75 37]
 [62 32 67 30 67]
 [29 68 49 47 45]
 [53 38 31 14 56]
 [61 62 20 42 53]]


In [69]:
# check array dimension
print(c.shape)

(5, 5)


In [70]:
#check no. of dimensions
print(c.ndim)

2


In [71]:
# no. of elements in an array 
print(c.size)

25


In [72]:
# checking the data type in the array 
print(c.dtype)

int32


In [73]:
# mathematical Operaion on numpy array
a=[1,2,3,4,5]
b=[6,7,8,9,10]
print(a+b) #concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [74]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 4 0]
 [8 5 7]
 [9 4 2]]
[[12 12 13]
 [11 19 19]
 [11 16 17]]


In [75]:
print(a+b)

[[15 16 13]
 [19 24 26]
 [20 20 19]]


In [76]:
print(a-b)

[[ -9  -8 -13]
 [ -3 -14 -12]
 [ -2 -12 -15]]


In [77]:
print(a*b)

[[ 36  48   0]
 [ 88  95 133]
 [ 99  64  34]]


In [78]:
print(a/b)

[[0.25       0.33333333 0.        ]
 [0.72727273 0.26315789 0.36842105]
 [0.81818182 0.25       0.11764706]]


In [81]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 7 5]
 [4 4 2]
 [4 1 7]]
[[15 13 14]
 [14 18 12]
 [17 18 12]]


In [84]:
# add functions
print(np.add(a,b))

[[23 20 19]
 [18 22 14]
 [21 19 19]]


In [85]:
# subtract function
print(np.subtract(a,b))

[[ -7  -6  -9]
 [-10 -14 -10]
 [-13 -17  -5]]


In [86]:
# multiply function 
print(np.multiply(a,b))

[[120  91  70]
 [ 56  72  24]
 [ 68  18  84]]


In [87]:
# divide function
print(np.divide(a,b))

[[0.53333333 0.53846154 0.35714286]
 [0.28571429 0.22222222 0.16666667]
 [0.23529412 0.05555556 0.58333333]]


In [88]:
# Array Manipulation 
a=np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[9 4 3]
 [3 6 8]]
(2, 3)


In [91]:
# transpose: is nothing if the array is 2,3 
# then transpose will convert it into 3,2
trans = np.transpose(a)
print(trans)
print(trans.shape)

[[9 3]
 [4 6]
 [3 8]]
(3, 2)


In [92]:
# another way of transpose
a=np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[1 2 2]
 [5 1 7]]
(2, 3)


In [93]:
trans2= a.T
print(trans2)
print(trans2.shape)

[[1 5]
 [2 1]
 [2 7]]
(3, 2)


In [94]:
# reshaping an array
a=np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[2 4 7]
 [2 6 5]]
(2, 3)


In [95]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[2 4]
 [7 2]
 [6 5]]
(3, 2)
