Numpy- Numerical Python 

Advantages of numpy Arrays:
 - Allows several Mathematical Operations
 - Faster Operations

Numpy is python Librray, Library are nothing but premade function or premade classes which are stored in a Python File

In [1]:
import numpy as np

In [2]:
# lets check the running time of List and Numpy Array
from time import process_time

In [3]:
# time taken by a list
a=[i for i in range(10000)]

starttime=process_time()

a=[i+5 for i in a]

endtime= process_time()

print(endtime-starttime)

0.0


In [4]:
# lets check with numpy array
a=np.array([i for i in range(10000)])

starttime=process_time()

a+=5

endtime=process_time()

print(endtime-starttime)

0.0


In [7]:
# creating Numpy array 
# list
a=[1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [8]:
# numpy array 
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
# creating 1D Array 
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
# we can check shape of this numpy array
# this shape function array will give us 
# rows and columns of that particular array
a.shape
# only four Columns


(4,)

In [12]:
# to check the dimensions of the array
print(a.ndim)

1


In [13]:
# lets create two dimensionnal array 
# 2d array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
b.shape

(2, 3)

In [15]:
# let create another array with float dtype
c=np.array([(1,2,3,4),(5,6,7,8)],dtype='float')
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [17]:
c=np.array([[1,2,3,4],[5,6,7,8]],dtype='float')
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [18]:
c.shape

(2, 4)

In [19]:
c.ndim

2

In [20]:
# place holders in array 
# initial holders in Numpy arrays 
# create a numpy array of zeros
a=np.zeros((4,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# creat5e nump array of ones
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
b=np.ones((5))
b

array([1., 1., 1., 1., 1.])

In [25]:
b=np.ones((5,1))
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [22]:
# create an array of an particular value
c=np.full((5,4),10)
# here 5,4 is matrix shape (5 rows and 4 columns)
# and 10 is the value for that array
print(c)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [30]:
c=np.full((10),9)
c

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [31]:
c=np.full((10,1),9)
c

array([[9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9],
       [9]])

In [33]:
# create an identity matrix
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.eye(5,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
a=np.eye(10,7)
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [36]:
b=np.eye(6)
print(b)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [37]:
# create a numpy array with random Values
b=np.random.random((3,4))
print(b)
# the value will lie between 0 to 1


[[0.25659467 0.36007188 0.45760726 0.53751444]
 [0.5277058  0.4791937  0.00934361 0.57366596]
 [0.53474357 0.83229446 0.00143191 0.87939656]]


In [38]:
# create a random array with random integers within a specific range 
c=np.random.randint(10,20,10)
c

array([13, 17, 17, 12, 19, 19, 15, 14, 15, 12])

In [45]:
c=np.random.randint(10,20,(5,5))
c
# 5 rows and 5 columns

array([[18, 14, 14, 13, 14],
       [13, 18, 19, 19, 15],
       [17, 18, 13, 19, 19],
       [16, 16, 10, 17, 19],
       [12, 19, 10, 18, 15]])

In [46]:
# create and array of evenly spaced values
a=np.linspace(10,30,5)
print(a)
# but all the these 5 values from the range 10 to 30,
# will be evenly spaced


[10. 15. 20. 25. 30.]


In [48]:
a=np.linspace(10,30,4)
print(a)

[10.         16.66666667 23.33333333 30.        ]


In [49]:
a=np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]


In [50]:
# another method of getting evenly spaced values
# array of evenly spaced values
# specifying the steps
a=np.arange(10,30,5)
print(a)

[10 15 20 25]


In [52]:
# convert a list to a numpy array 
list2 = [10,20,20,20,50]
a=np.array(list2)
print(a)
print(type(a))

[10 20 20 20 50]
<class 'numpy.ndarray'>


In [74]:
# Analysing a numpy array 
# analysing is nothing but getting information from that particular Array 
# just inspecting an array
c=np.random.randint(10,90,(5,5))
print(c)

[[83 62 40 67 71]
 [83 15 15 13 47]
 [23 87 84 78 14]
 [21 87 73 16 21]
 [46 17 40 54 24]]


In [75]:
# check array dimension
print(c.shape)

(5, 5)


In [76]:
#check no. of dimensions
print(c.ndim)

2


In [77]:
# no. of elements in an array 
print(c.size)

25


In [78]:
# checking the data type in the array 
print(c.dtype)

int32


In [79]:
# mathematical Operaion on numpy array
a=[1,2,3,4,5]
b=[6,7,8,9,10]
print(a+b) #concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [87]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print("a: \n",a)
print("\n")
print("b: \n",b)

a: 
 [[6 1 8]
 [8 7 4]
 [4 6 5]]


b: 
 [[16 10 16]
 [11 10 14]
 [16 19 17]]


In [85]:
print(a+b)

[[25 21 20]
 [18 21 23]
 [21 16 22]]


In [88]:
print(a-b)

[[-10  -9  -8]
 [ -3  -3 -10]
 [-12 -13 -12]]


In [90]:
print(b-a)

[[10  9  8]
 [ 3  3 10]
 [12 13 12]]


In [89]:
print(a*b)

[[ 96  10 128]
 [ 88  70  56]
 [ 64 114  85]]


In [91]:
print(a/b)

[[0.375      0.1        0.5       ]
 [0.72727273 0.7        0.28571429]
 [0.25       0.31578947 0.29411765]]


In [92]:
print(b/a)

[[ 2.66666667 10.          2.        ]
 [ 1.375       1.42857143  3.5       ]
 [ 4.          3.16666667  3.4       ]]


In [95]:
# add functions
print(np.add(a,b))
# print(a+b)

[[22 11 24]
 [19 17 18]
 [20 25 22]]


In [96]:
# Subtract ()
print(np.subtract(a,b))

[[-10  -9  -8]
 [ -3  -3 -10]
 [-12 -13 -12]]


In [97]:
# multiply ()
print(np.multiply(a,b))

[[ 96  10 128]
 [ 88  70  56]
 [ 64 114  85]]


In [98]:
print(np.divide(a,b))

[[0.375      0.1        0.5       ]
 [0.72727273 0.7        0.28571429]
 [0.25       0.31578947 0.29411765]]


In [100]:
a=np.random.randint(10,100,(2,3))
a

array([[21, 32, 57],
       [48, 50, 40]])

In [101]:
# transpose: is nothing if the array is 2,3 
# then transpose will convert it into 3,2
trans = np.transpose(a)
print(trans)

[[21 48]
 [32 50]
 [57 40]]


In [102]:
print(trans.shape)

(3, 2)


In [105]:
# another way of transpose
a=np.random.randint(1,10,(2,3))
print(a)
print("Shape of the Array",a.shape)

[[4 5 3]
 [6 1 6]]
Shape of the Array (2, 3)


In [106]:
trans=a.T
print(trans)
print("Shape of the Array",trans.shape)

[[4 6]
 [5 1]
 [3 6]]
Shape of the Array (3, 2)


In [107]:
# reshaping an array
a=np.random.randint(1,10,(2,3))
print(a)
print("Shape of the Array",a.shape)

[[9 7 3]
 [5 9 2]]
Shape of the Array (2, 3)


In [109]:
# reshaping the above array 
b=a.reshape(3,2)
print(b)
print("Shape of the Array",b.shape)

[[9 7]
 [3 5]
 [9 2]]
Shape of the Array (3, 2)
